### ISSUE TITLE
Disallow failures on nightly

### ISSUE THREAD

**Issue by koute** [astraw/bui-backend#1]
FYI, `cargo-web` 0.4.2 is building again on the newest nightly, so you can revert commit d2ca064. (:

**Comment by astraw** [comment]
Hmm, I still get a failure on nightly if I revert that commit: https://travis-ci.org/astraw/bui-backend/jobs/322690871

**Comment by koute** [comment]
Ah right, sorry for the confusion! It seems you're using the `jsonwebtoken` crate which requires `ring`.

I saw that you using `cargo-web` (whose compilation was also failing on nightly due to `ring`) and that you've allowed failures on nightly, so I thought to give you a heads-up that the issue is fixed already, but I failed to check whenever you have any other stuff which uses `ring`.

Sorry for jumping the gun!

**Comment by astraw** [comment]
No worries and thanks for your work on stdweb and cargo-web.
